config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/test'
  resources :articles, only: [:index, :create]
  resources :students, only: [:index]

end

app/models/animal.rb
class Animal < ActiveRecord::Base
  belongs_to :tribe

  self.inheritance_column = :race

  scope :lions, ->{where race: "Animal::Lion"}
  scope :meerkats, ->{where race: "Animal::Meerkat"}
  scope :wild_boars, ->{where race: "Animal::WildBoar"}

  def talk
    logger = Logger.new(STDOUT)
    logger.level = Logger::DEBUG
    logger.info "Zoo animals welcome you"
  end

  class << self
    def races
      %w(Lion WildBoar Meerkat)
    end
  end
end

app/models/animal/lion.rb
class Animal::Lion < Animal
  def talk
    "It means no worries for the rest of your days"
  end
end

app/models/animal/meerkat.rb
class Animal::Meerkat < Animal
  def talk
    "Hakuna Matata, what a wonderful phrase !"
  end
end

app/models/animal/wild_boar.rb
class Animal::WildBoar < Animal
  def talk
    "Hakuna Matata! Ain't no passing craze"
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/class_room.rb
class ClassRoom < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/models/tribe.rb
class Tribe < ActiveRecord::Base
  has_many :animals

  delegate :lions, :meerkats, :wild_boars, to: :animals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all.order(:title)
  end

  def create
    @article = Article.new article_params
    if @article.save
    else
    end
  end

  private
  def article_params
    params.require(:article).permit :title, :body
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def test

  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all.order :name
    respond_to do |format|
      format.html
      format.xlsx{render xlsx: 'index', filename: "students.xlsx"}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= form_for Article.new, remote: true do |f| %>
  <div class="fields">
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </div>
  <div class="fields">
    <%= f.label :body %><br/>
    <%= f.text_field :body %>
  </div>
  <div class="controls">
    <%= f.submit "Create" %>
  </div>
<% end %>

app/views/articles/index.html.erb
<h1>New Article</h1>
<%= render "form" %>
<h1>All Article</h1>
<ul class="articles">
  <% @articles.each do |article| %>
    <li class="article">
      <p><%= link_to article.title, "#" %></p>
      <p><%= article.body %></p>
      <hr>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VibloMonth3th</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to Awsome Site</h1>
<p>This is page to check normal ajax</p>
<p><strong>Click below button to add content for page by ajax</strong></p>
<%= button_tag "Append content now!", type: "button", id: "append_content" %>

app/views/pages/test.html.erb
<p>
  <strong>
    Creates a button element that defines a submit button, resetbutton or a generic button which can be used in JavaScript, for example. You can use the button tag as a regular submit tag but it isn’t supported in legacy browsers. However, the button tag allows richer labels such as images and emphasis, so this helper will also accept a block.
  </strong>
</p>

app/views/students/index.html.erb
<div class="row">
  <div class="container">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>No</th>
          <th>ID</th>
          <th>Name</th>
          <th>Student Age</th>
          <th>Student Phone Number</th>
          <th>Student Email</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @students.each.with_index(1) do |student, i| %>
          <tr>
            <td><%= i %></td>
            <td><%= student.id %></td>
            <td><%= student.name %></td>
            <td><%= student.age %></td>
            <td><%= student.phone_number %></td>
            <td><%= student.email %></td>
            <td><%#= link_to "Download", axlsx_index_path(id: student.try(:id)) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="container">
    <p>
      Download:
      <%= link_to "Download", students_path(format: :xlsx) %>
    </p>
  </div>
</div>